services:

  bot:
    build: ./bot
    image: bot
    container_name: bot
    volumes:
      - logs:/logs

  captcha:
    build: ./captcha
    image: captcha
    container_name: captcha
    volumes:
      - captcha-images:/data
      - logs:/logs

  scheduler:
    build: ./scheduler
    image: scheduler
    container_name: scheduler
    volumes:
      - logs:/logs

volumes:
  captcha-images:
  logs:

# docker-compose command
# > docker-compose up --build -d