services:

  bot:
    build: ./bot
    image: bot
    container_name: bot
    volumes:
      - logs:/logs

  captcha:
    build: ./captcha
    image: captcha
    container_name: captcha
    volumes:
      - captcha-images:/data
      - logs:/logs

  scheduler:
    build: ./scheduler
    image: scheduler
    container_name: scheduler
    volumes:
      - logs:/logs

  database:
    build: ./database
    image: database
    container_name: database
    volumes:
      - logs:/logs
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root 
    ports:
      - "5050:80"

volumes:
  captcha-images:
  logs:

# docker-compose command
# > docker-compose up --build -d