services:

  bot:
    build: ./bot
    image: bot
    container_name: bot

  captcha:
    build: ./captcha
    image: captcha
    container_name: captcha
    volumes:
      - captcha-images:/data

  scheduler:
    build: ./scheduler
    image: scheduler
    container_name: scheduler
    
volumes:
  captcha-images:

# docker-compose command
# > docker-compose up --build -d